### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by pjht** [pjht/SSSP-Core#11]
This is a todo list

Recipies:

- [ ] Phosphor ore mined -> 2-4 phosphor
- [ ] Phosphor +water bucket + 4x empty bottle -> 4x phosphoric acid bottle
- [ ] Boron ore in a furnace -> boron
- [ ] Hydrogen bottle + clorine bottle + water bottle -> hydrocloric acid bottle + 2x empty bottle
- [ ] Hydrocloric acid bottle + boron -> boric acid 
- [ ] Blank chip + phosphoric acid bottle + boric acid + blueprint -> chip + blueprint + empty bottle
- [ ] 2x coal -> coke
- [ ] Iron nugget + clorine bottle + water bottle -> ferric acid bottle + empty bottle 
- [ ] PCB blueprint + ferric acid bottle + blank PCB -> empty PCB + PCB blueprint + empty bottle
